-- =============================================
-- EcoRural 数据库表结构设计
-- 低碳农业积分平台数据模型
-- =============================================

-- 1. 用户档案表 (profiles)
-- 扩展 Supabase auth.users，存储用户个性化数据
-- =============================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT NOT NULL DEFAULT '低碳新用户',
  avatar_url TEXT,
  green_coins INTEGER NOT NULL DEFAULT 0,
  total_carbon_saved DECIMAL(10, 2) NOT NULL DEFAULT 0.0,
  total_calories_burned INTEGER NOT NULL DEFAULT 0,
  user_title TEXT DEFAULT '绿芽',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_profiles_green_coins ON public.profiles(green_coins DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_carbon_saved ON public.profiles(total_carbon_saved DESC);

-- =============================================
-- 2. 低碳行为记录表 (activities)
-- 记录每一次运动或打卡行为
-- =============================================
CREATE TABLE IF NOT EXISTS public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('walk', 'bike', 'bus', 'plant_tree', 'checkin')),
  amount DECIMAL(10, 2) NOT NULL,
  carbon_earned DECIMAL(10, 2) NOT NULL DEFAULT 0,
  points_earned INTEGER NOT NULL DEFAULT 0,
  duration_minutes INTEGER,
  distance_km DECIMAL(10, 2),
  route_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_activities_user_id ON public.activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_type ON public.activities(type);
CREATE INDEX IF NOT EXISTS idx_activities_created_at ON public.activities(created_at DESC);

-- 用户行为统计函数（用于触发器）
CREATE OR REPLACE FUNCTION update_user_stats()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.profiles
  SET
    green_coins = green_coins + NEW.points_earned,
    total_carbon_saved = total_carbon_saved + NEW.carbon_earned,
    total_calories_burned = total_calories_burned + COALESCE(NEW.duration_minutes * 5, 0),
    updated_at = NOW()
  WHERE id = NEW.user_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 自动更新用户统计的触发器
CREATE TRIGGER trg_update_user_stats
AFTER INSERT ON public.activities
FOR EACH ROW
EXECUTE FUNCTION update_user_stats();

-- =============================================
-- 3. 农产品商品表 (products)
-- 积分集市商品信息
-- =============================================
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price_in_coins INTEGER NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  category TEXT NOT NULL DEFAULT 'other',
  origin TEXT,
  image_url TEXT,
  carbon_reduction DECIMAL(10, 2) DEFAULT 0.5,
  farmer_info JSONB DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_price ON public.products(price_in_coins);
CREATE INDEX IF NOT EXISTS idx_products_active ON public.products(is_active);

-- =============================================
-- 4. 兑换订单表 (orders)
-- 记录商品兑换信息
-- =============================================
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT ASIDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL UNIQUE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'shipped', 'completed', 'cancelled')),
  total_price INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  shipping_address JSONB DEFAULT '{}'::jsonb,
  farmer_revenue DECIMAL(10, 2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paid_at TIMESTAMPTZ,
  shipped_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_order_no ON public.orders(order_no);

-- 生成订单号的函数
CREATE OR REPLACE FUNCTION generate_order_no()
RETURNS TEXT AS $$
BEGIN
  RETURN 'ECO' || TO_CHAR(NOW(), 'YYYYMMDDHH24MISS') || LPAD(FLOOR(RANDOM() * 10000)::TEXT, 4, '0');
END;
$$ LANGUAGE plpgsql;

-- 创建订单时的触发器
CREATE OR REPLACE FUNCTION set_order_defaults()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.order_no IS NULL THEN
    NEW.order_no := generate_order_no();
  END IF;
  IF NEW.created_at IS NULL THEN
    NEW.created_at := NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_order_defaults
BEFORE INSERT ON public.orders
FOR EACH ROW
EXECUTE FUNCTION set_order_defaults();

-- =============================================
-- 5. 用户称号自动更新函数
-- 根据累计减碳量自动更新称号
-- =============================================
CREATE OR REPLACE FUNCTION update_user_title()
RETURNS TRIGGER AS $$
DECLARE
  new_title TEXT;
BEGIN
  IF NEW.total_carbon_saved >= 50 THEN
    new_title := '金穗';
  ELSIF NEW.total_carbon_saved >= 10 THEN
    new_title := '青苗';
  ELSE
    new_title := '绿芽';
  END IF;

  IF NEW.user_title != new_title OR NEW.user_title IS NULL THEN
    NEW.user_title := new_title;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 创建触发器
CREATE TRIGGER trg_update_user_title
BEFORE INSERT OR UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION update_user_title();

-- =============================================
-- 6. Row Level Security (RLS) 安全策略
-- =============================================

-- 启用 RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- profiles: 用户只能查看和修改自己的数据
CREATE POLICY "用户只能查看自己的档案" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "用户可以更新自己的档案" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- activities: 用户只能操作自己的行为记录
CREATE POLICY "用户只能查看自己的行为记录" ON public.activities
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户可以插入自己的行为记录" ON public.activities
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- products: 所有用户都可以查看商品
CREATE POLICY "所有用户都可以查看商品" ON public.products
  FOR SELECT USING (true);

-- orders: 用户只能查看和创建自己的订单
CREATE POLICY "用户只能查看自己的订单" ON public.orders
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户可以创建订单" ON public.orders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- =============================================
-- 7. 基础数据种子数据
-- =============================================

-- 示例商品数据
INSERT INTO public.products (name, description, price_in_coins, stock, category, origin, carbon_reduction, farmer_info, image_url)
VALUES
(
  '平谷有机大桃',
  '正宗平谷大桃，自然成熟，甜度高',
  500,
  100,
  'fruit',
  '北京市平谷区',
  0.8,
  '{"name": "王大叔", "avatar": "farmer1", "quote": "种桃30年，桃桃甜又香！"}'::jsonb,
  'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=400'
),
(
  '密云有机小米',
  '农家自种小米，熬粥香糯',
  300,
  200,
  'grain',
  '北京市密云区',
  0.5,
  '{"name": "李大娘", "avatar": "farmer2", "quote": "小米养胃又养生！"}'::jsonb,
  'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400'
),
(
  '延庆有机苹果',
  '高山苹果，昼夜温差大，糖分足',
  800,
  150,
  'fruit',
  '北京市延庆区',
  0.6,
  '{"name": "张大哥", "avatar": "farmer3", "quote": "苹果脆甜，产地直发！"}'::jsonb,
  'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=400'
)
ON CONFLICT DO NOTHING;

-- =============================================
-- 8. 实用视图
-- =============================================

-- 用户排行榜视图
CREATE OR REPLACE VIEW public.user_leaderboard AS
SELECT
  p.id,
  p.username,
  p.avatar_url,
  p.user_title,
  p.green_coins,
  p.total_carbon_saved,
  RANK() OVER (ORDER BY p.total_carbon_saved DESC) as carbon_rank,
  RANK() OVER (ORDER BY p.green_coins DESC) as coins_rank,
  COUNT(a.id) as activity_count
FROM public.profiles p
LEFT JOIN public.activities a ON p.id = a.user_id
GROUP BY p.id
ORDER BY p.total_carbon_saved DESC;

-- 商品分类统计
CREATE OR REPLACE VIEW public.category_stats AS
SELECT
  category,
  COUNT(*) as product_count,
  SUM(stock) as total_stock,
  AVG(price_in_coins) as avg_price
FROM public.products
WHERE is_active = true
GROUP BY category;

-- =============================================
-- 9. 常用查询示例
-- =============================================

-- 查询用户最近7天行为统计
-- SELECT * FROM public.activities
-- WHERE user_id = '用户ID'
-- AND created_at >= NOW() - INTERVAL '7 days'
-- ORDER BY created_at DESC;

-- 查询用户订单历史
-- SELECT o.*, p.name as product_name, p.image_url
-- FROM public.orders o
-- JOIN public.products p ON o.product_id = p.id
-- WHERE o.user_id = '用户ID'
-- ORDER BY o.created_at DESC;

-- 兑换商品并创建订单
-- 1. 扣除用户积分
-- 2. 创建订单记录
-- 3. 更新商品库存
